create table item (
    ID              INTEGER NOT NULL PRIMARY KEY,
    BARCODE         CHARACTER VARYING (255),
    IDENTIFICATION  CHARACTER VARYING (255),
    QUANTITY        INTEGER,
    UNITOFMEASURE   CHARACTER VARYING (255),
    IMAGE           CHARACTER VARYING (255)
);

create table unitofmeasure (
    ID              INTEGER, NOT NULL PRIMARY KEY,
    SHORTID         CHARACTER VARYING (255),
    DESCRIPTION     CHARACTER VARYING (255),
    GREATNESS       CHARACTER VARYING (255)
);

create table manufacturer (
    ID              INTEGER, NOT NULL PRIMARY KEY,
    COMERCIAL_NAME  CHARACTER VARYING (255),
    BUSINESS_NAME   CHARACTER VARYING (255),

);

create table company (
    ID              INTEGER, NOT NULL PRIMARY KEY,
    COMERCIAL_NAME  CHARACTER VARYING (255),
    BUSINESS_NAME   CHARACTER VARYING (255),

);